export const Data = [
    {
        id: 1,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "To’langan",
        time: "20.11.2023  11:30",
        action: "Chekni yuklash",
    },
    {
        id: 2,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "Qarzdorlik",
        time: "-",
        action: "To’lov kiritish",
    },
    {
        id: 3,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "To’lanmagan",
        time: '-',
        action: "To’lov kiritish",
    },
    {
        id: 4,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "To’langan",
        time: "20.11.2023  11:30",
        action: "Chekni yuklash",
    },
    {
        id: 5,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "To’lanmagan",
        time: "20.11.2023  11:30",
        action: "Chekni yuklash",
    },
    {
        id: 6,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "Qarzdorlik",
        time: "-",
        action: "To’lov kiritish",
    },
    {
        id: 7,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "To’lanmagan",
        time: "-",
        action: "To’lov kiritish",
    },
    {
        id: 8,
        key: "1",
        number: "100001/AA",
        name: "Jumaniyozov Umidbek",
        course: "Frontend basic",
        payment: "800 000 so`m",
        status: "To’langan",
        time: "20.11.2023  11:30",
        action: "Chekni yuklash",
    },
];