export const Data = [
    {
        id: 1,
        key: "1",
        fullName: "Umidbek Jumaniyozov",
        registerTime: "20.11.2023  11:30",
        whichCourse: "Kompyuter savodxonligi",
        action: "Ro’yhatdan o’tgan",
        accessTime: "20.11.2023  11:30",
        paymentStatus: "Jarayonda",
    },
    {
        id: 2,
        key: "1",
        fullName: "Umidbek Jumaniyozov",
        registerTime: "20.11.2023  11:30",
        whichCourse: "Kompyuter savodxonligi",
        action: "O’qishni rad qildi",
        accessTime: "20.11.2023  11:30",
        paymentStatus: "Rad qilindi",
    },
    {
        id: 3,
        key: "1",
        fullName: "Umidbek Jumaniyozov",
        registerTime: "20.11.2023  11:30",
        whichCourse: "Kompyuter savodxonligi",
        action: "Guruhga yozildi",
        accessTime: "20.11.2023  11:30",
        paymentStatus: "Jarayonda",
    },
    {
        id: 3,
        key: "1",
        fullName: "Umidbek Jumaniyozov",
        registerTime: "20.11.2023  11:30",
        whichCourse: "Kompyuter savodxonligi",
        action: "O’qishni boshlagan",
        accessTime: "20.11.2023  11:30",
        paymentStatus: "To’landi",
    },
]; 